### ISSUE TITLE
Remove the need for `&()`

### ISSUE THREAD

**Issue by jprochazk** [jprochazk/garde#100]
Currently, the definition of the `Validate` looks like this when simplified:

```rust
trait Validate {
    type Context = ();

    fn validate(&self, ctx: &Self::Context) -> garde::Result;
}
```

The real trait has some extra parameters used to implement certain functionality more efficiently.

The problem with the above is that you _always_ have to pass in a context to `Validate`, even if your type doesn't require one! It's not a _huge_ issue, but it's just an eyesore.

We can change the trait definitions to something like this:

```rust
trait Validate {
    fn validate(&self) -> Result<()>;
}

trait ValidateWith {
    type Context;

    fn validate_with(&self, ctx: &Self::Context) -> Result<()>;
}

impl<T: Validate> ValidateWith for T {
    type Context = ();
    
    fn validate_with(&self, _: &Self::Context) -> Result<()> {
        Validate::validate(self)
    }
}
```

- The `ValidateWith` trait is introduced, with an associated `Context` type.
- The base `Validate` trait no longer has an associated context.
- There is a blanket impl of `ValidateWith` for any type which implements `Validate`, using a unit context.

Internally, the proc macro will switch between deriving `Validate` and `ValidateWith` depending on if a context has been provided or not.

The context passed to `#[garde(dive)]` fields will also depend on which trait is being derived.

- In derived `Validate` impls, `#[garde(dive)]` fields will provide a `&()` context.
- In derived `ValidateWith` impls, `#[garde(dive)]` fields will propagate the context.

The result is that you can now drop the `&()` from all validate calls that don't actually need a context, which as GitHub code search may suggest is the vast majority of them.

The one downside is a _slight_ tradeoff in ergonomics. You now have to import `garde::ValidateWith` in any place where you call `validate_with`, instead of the usual `garde::Validate`. This shouldn't be _too_ big of a deal as `rust-analyzer` will automatically suggest this change.

We will alias the `Validate` proc macro as `ValidateWith` to also make it possible to use `#[derive(ValidateWith)]` instead, just in case users try to derive it that way.

```rust
use garde::{Validate, ValidateWith};

#[derive(Validate)]
struct Thing {
    #[garde(length(min = 1))]
    v: &'static str,
}

Thing { v: "ok" }.validate().unwrap(); // no `&()`!
```

```rust
use garde::{Validate, ValidateWith};

struct Ctx {
    min: usize,
}

#[derive(Validate)]
#[garde(context(Ctx as ctx)]
struct Thing {
    #[garde(length(min = ctx.min))]
    v: &'static str,
}

let ctx = Ctx { min: 1 };
Thing { v: "ok" }.validate_with(&ctx).unwrap();
```

**Comment by jprochazk** [comment]
This also means `custom` validators don't need the context parameter anymore, either! We can dispatch them without a context in derived `Validate` impls.

**Comment by lasantosr** [comment]
It seems that you could merge both traits into one for me, I've included an example on the other issue: https://github.com/jprochazk/garde/issues/39#issuecomment-2027677520

**Comment by jprochazk** [comment]
Opened a separate issue for the 2nd part of this: https://github.com/jprochazk/garde/issues/104
