### ISSUE TITLE
Can't validate inner type of optional vector

### ISSUE THREAD

**Issue by kudlatyamroth** [jprochazk/garde#111]
i have struct like this:
```
pub static REGEXP_ONE: Lazy<Regex> = Lazy::new(|| Regex::new(r"^([A-z0-9\-]+)$").unwrap());

#[derive(garde::Validate)]
struct Test {
    #[garde(inner(pattern(REGEXP_ONE)))]
    items: Option<Vec<String>>,
}
```

and clippy give me error:
`note: required for `std::vec::Vec<std::string::String>` to implement `garde::rules::pattern::Pattern``

error goes away if i make inner in inner like this:
```
#[garde(inner(inner(pattern(REGEXP_ONE))))]
```

and if i have Option<Option<Vec<String>>> i will need 3x inner

**Comment by jprochazk** [comment]
Yes, that's how `inner` works. There are no plans to change that.

**Comment by jprochazk** [comment]
Actually, reopening this as a docs issue, because it isn't mentioned anywhere that you're supposed to nest them.

**Comment by jprochazk** [comment]
Done in https://github.com/jprochazk/garde/commit/05e2b85d54b716861d32d6d10b62f335e2ddbc84
