### ISSUE TITLE
Allow range to have min/max int for value in float

### ISSUE THREAD

**Issue by kudlatyamroth** [jprochazk/garde#112]
It would be great to have this possible:

```
    #[garde(range(min = 0, max = 100))]
    pub value: f64,
 ```

now it gives error:
```
expected `f64`, found integer
help: use a float literal: `0.0`
```

**Comment by jprochazk** [comment]
You have to use a float literal like that error message is telling you, just like with regular rust syntax (`0.0..100.0`)

**Comment by jprochazk** [comment]
In general, I don't want to special case any rule in this library based on the provided typename. In this case it'd require something like:
```rust
if field_type.to_string() == "f64" {
  quote!(range(#min as f64, #max as f64))
} else {
  quote!(range(#min, #max))
}
```

That's very brittle, because there's no guarantee that the field is actually [the primitive](https://doc.rust-lang.org/std/primitive.f64.html).

**Comment by kudlatyamroth** [comment]
it would be very helpful for validation openapi with minimum and maximum
