### ISSUE TITLE
Add more information in the Error Type.

### ISSUE THREAD

**Issue by BennyPLS** [jprochazk/garde#115]
I think the current implementation, which includes only a message and it's the responsibility of the rule, is a little cumbersome. If I want a different error message, I need to create a custom rule. If this applies to all the rules, I believe it's worth considering programmatic access to the validation type and constraint info that failed or the constraints (Like in the param data in the [Validator Crate](https://github.com/Keats/validator)) or the option to override the error message. I expect comments on this or even if it’s relatively easy to implement with the current state of this library or even if it's the plan.

Thanks for your time.

**Comment by jprochazk** [comment]
Please search through issues before opening new ones:
- https://github.com/jprochazk/garde/issues/3
- https://github.com/jprochazk/garde/issues/7
- https://github.com/jprochazk/garde/issues/105
