### ISSUE TITLE
Incorrect email validation

### ISSUE THREAD

**Issue by iUnstable0** [jprochazk/garde#125]
This email validator incorrectly accepts `test@ok` as a valid input. While it follows the [HTML specification](https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address) for email address validation, the regex provided on that website also matches emails without a top-level domain (TLD), such as `test@gmailcom`. This is problematic for several reasons:

1. **Public-Facing Applications**: For public-facing applications, accepting emails without a TLD can lead to invalid user inputs, causing potential issues with email delivery and user verification processes.

2. **Rare Usage in Development**: Even in development environments, it is rare to see local email addresses without a TLD. Most development setups use valid TLDs to simulate real-world scenarios. (if im being honest they js use their personal or burner mail lol)

To address these concerns, I suggest enforcing a stricter validation that requires a TLD. This can be achieved by modifying the regex to ensure the presence of a TLD. Here is an example of a stricter regex:

```regex
/^[-a-zA-Z0-9_.]+@[-a-zA-Z0-9]+\.[a-zA-Z]{2,4}$/
```

**Comment by jprochazk** [comment]
Email validation done by this library is meant to be _purely syntactical_. It should serve only as an early-out for obviously garbage email addresses. If you want to ensure that the email address is actually valid, the only reliable way to do so is to send an email to it.

Side note: Please don't post issues with bodies written by LLMs, it's a bad look.
