### ISSUE TITLE
feature request: support for stdlib `LazyLock` in regex

### ISSUE THREAD

**Issue by Fogapod** [jprochazk/garde#129]
garde currently supports static regexes via `once_cell`: https://github.com/jprochazk/garde/blob/be00ddddf8de14530ee890ccfdbaf0b13fb32852/garde/src/rules/pattern.rs#L147-L163

stdlib added LazyLock recently: https://doc.rust-lang.org/std/sync/struct.LazyLock.html

would you be open for a PR adding support for these? this would mean raising MSRV to `1.80`

**Comment by jprochazk** [comment]
I'd like to wait until at least 1.82 before setting the MSRV to 1.80
