### ISSUE TITLE
Support for #[garde(inner(dive))]

### ISSUE THREAD

**Issue by ramiroaisen** [jprochazk/garde#133]
Just a probably silly question...

In this struct
```rs
struct Foo {
  #[garde(length(min = 1))]
  bar: Vec<MyType>
}
```

where MyType implements Validate, will the Validate logic be called for the inner MyType type?
Do o need to add #[garde(dive)] to it?

Same question about Option

**Comment by jprochazk** [comment]
```rust
#[derive(Validate)]
struct Foo {
  #[garde(dive)]
  bar: Vec<MyType>,
}
```

Calls `validate` on each item.

```rust
#[derive(Validate)]
struct Foo {
  #[garde(length(min=1))]
  bar: Vec<MyType>,
}
```
Would check the length of the `Vec` itself, but not the items.

There is no such thing as `inner(dive)`.
