### ISSUE TITLE
Handling of Option fields in a struct

### ISSUE THREAD

**Issue by xifel** [jprochazk/garde#23]
Currently validators just break on fields that are wrapped in an Option. Would it be possible to support that? (transparently?)

**Comment by xifel** [comment]
Interesting because that's another angle that I haven't thought about.
My idea was more like have an optional string be validated (maybe) like this:
```rust
#[derive(Validate)]
struct MyStruct {
    #[garde(alphanumeric)]
    field: Option<String>,
}
```
As far as I understand with dive I would have to define my own String on which I could then define a alphanumeric rule, right?

**Comment by jprochazk** [comment]
Yep, I was just about to clarify. At the moment, I'm not too sure how something like your snippet should work.

My initial thoughts are an `inner` could make this work. Something like `inner(length(min=1, max=100))`. For example:

```rust
#[derive(Validate)]
struct MyStruct {
    #[garde(inner(alphanumeric))]
    field: Option<String>,
}

// derives an impl similar to:
impl Validate for MyStruct {
    type Context = ();
    fn validate(&self, ctx: &Self::Context) -> garde::Result {
        Errors::fields(|errors| {
            errors.insert("field", Errors::simple(|errors| {
                garde::rules::inner::apply(&self.field, |value| {
                    errors.push(garde::rules::alphanumeric::apply(value));
                });
            });
        })
        .finish()
    }
}
```

What do you think?

**Comment by omid** [comment]
I think `Option` is a unique case and it should always be applied to the inner. (except for `required`)

**Comment by George-Miao** [comment]
Any update on the `Option` support?

**Comment by jprochazk** [comment]
As of [`v0.12`](https://github.com/jprochazk/garde/releases/tag/v0.12.0), all rules are now transparently applied to `Option` fields. Validation for `Option<T>` happens only if the `Option` is `Some`. To additionally require that it is `Some`, add the `required` rule.

On top of that, the derive macro now supports the `inner` modifier as described above.
