### ISSUE TITLE
Improve `ToString` implementation on `garde::Errors`

### ISSUE THREAD

**Issue by Altair-Bueno** [jprochazk/garde#26]
### Description

Current `ToString` implementation lacks a lot of details. 

### Current output 

For example, consider the following scheme:

```rs
#[derive(Debug, Serialize, Deserialize, Validate)]
struct Person {
    #[garde(ascii, length(min = 3, max = 25))]
    username: String,
    #[garde(length(min = 15))]
    password: String,
}
```
When fed with the following payload (JSON format), the current implementation only shows the first error message, instead of listing all errors

```text
// Input
{"username": "h", "password": "aaaaa"}
// ToString impl
length is lower than 3
// Debug impl
Fields({"password": Simple([Error { message: "length is lower than 15" }]), "username": Simple([Error { message: "length is lower than 3" }])})
```

### Expected behaviour

List all errors on some human readable form, like this

```text
`field.name`: length is lower than 15
`field.name2`: length is lower than 3
```

Also, provide a `serde::Serialize` implementation so we could provide JSON responses on REST APIs (related to https://github.com/jprochazk/garde/issues/12)

**Comment by jprochazk** [comment]
It's already possible to do this via `Errors::flatten()`, e.g.:

```rust
#[derive(Debug, Serialize, Deserialize, Validate)]
struct Person {
    #[garde(ascii, length(min = 3, max = 25))]
    username: String,
    #[garde(length(min = 15))]
    password: String,
}

let value = Person { username: "a".into(), password: "b".into() };
match value.validate(&()) {
  Ok(()) => {}
  Err(e) => {
    println!("{:?}", e.flatten());
  }
}
```

As for implementing `Serialize` for `Errors`, would you expect the output to use `flatten` or maintain the nested structure?

**Comment by Altair-Bueno** [comment]
> `println!("{:?}", e.flatten());`

But thats the debug impl, which contains information about the underling implementation. I don't feel confident exposing that kind of information to the public

> would you expect the output to use flatten or maintain the nested structure?

I think the best would be to emulate the output of other validation libraries, such as [zod](https://zod.dev/). Flatten is what zod uses

```ts
// Deno source code
import { z } from "https://deno.land/x/zod/mod.ts";
const scheme = const scheme = z.object({
	username: z.string(),
	age: z.number().min(18)
})
scheme.safeParse({username: 1, age: 10})
/*
{
  success: false,
  error: ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "number",
    "path": [
      "username"
    ],
    "message": "Expected string, received number"
  },
  {
    "code": "too_small",
    "minimum": 18,
    "type": "number",
    "inclusive": true,
    "exact": false,
    "message": "Number must be greater than or equal to 18",
    "path": [
      "age"
    ]
  }
]
    at handleResult (https://deno.land/x/zod@v3.20.2/types.ts:94:19)
    at ZodObject.safeParse (https://deno.land/x/zod@v3.20.2/types.ts:231:12)
    at <anonymous>:2:8
}
*/
```

**Comment by jprochazk** [comment]
> But thats the debug impl, which contains information about the underling implementation. I don't feel confident exposing that kind of information to the public

That was just an example. `flatten` returns a `Vec<(String, Error)>`, and `Error` implements `Display` (it just prints the error, e.g. `length is lower than 15`). You can see an example of the output [in snapshots](https://github.com/jprochazk/garde/blob/main/garde_tests/tests/rules/snapshots/email__email_invalid.snap). Does that not work for you?

> I think the best would be to emulate the output of other validation libraries

That does look like flattened output. I think this ties into https://github.com/jprochazk/garde/issues/7 and https://github.com/jprochazk/garde/issues/3 a bit. Ideally each rule would have a unique (machine-readable) error code, and you'd be able to provide your own, just like you could provide a custom error message.

I don't know if it's best to serialize the constraints (e.g. the `minimum: 18` in zod's output) together with the error messages, or leave those separate. I'm more inclined towards the latter.

**Comment by Altair-Bueno** [comment]
> Does that not work for you?

It does. Maybe we could add this to the current `ToString` implementation? 


> I don't know if it's best to serialize the constraint parameters (e.g. the minimum: 18 in zod's output) together with the error messages, or leave those separate. I'm more inclined towards the latter.

Maybe an enum, like `serde_json::Value`, that serves as metadata?

```jsonc
[
  {
    // ...
    "metadata": {
       "kind": "length",
       "min": 10
	}
  },
  // ...
]
```

**Comment by jprochazk** [comment]
As of https://github.com/jprochazk/garde/pull/28, the `Display` impl for `Errors` now uses `flatten`. The 2nd part (serializing errors) is split off to https://github.com/jprochazk/garde/issues/3.

**Comment by Altair-Bueno** [comment]
Looks great. Thanks!
