### ISSUE TITLE
Feature request: UTF-16 code units length validator

### ISSUE THREAD

**Issue by LeoniePhiline** [jprochazk/garde#40]
(Adjusted for `garde` from https://github.com/Keats/validator/issues/250)

The current `garde` crate provides built-in validators for various use cases, but it lacks a validator for checking the length of a string based on its UTF-16 code units. This feature request proposes the addition of a UTF-16 code units length validator to the crate.

The motivation behind this request stems from the need to match the behavior of the HTML textarea `maxlength` attribute, which counts UTF-16 code units. To provide better consistency between frontend and backend validation, it would be useful to have a validator that directly checks the length of a string based on its UTF-16 code units.

The new validator could be used as follows:

```rust
use garde::{Validate, Valid};

#[derive(Validate)]
struct Post<'a> {
    #[garde(length_utf16(min=32, max=65535))]
    message: &'a str,,
}
```

Replace `N` with the desired UTF-16 code unit count. Use the same `N` for the HTML `textarea`. 

`N` would be `max bytes / 2`, as UTF-16 code units are 2 bytes long.

This new validator would ensure that the code unit count limits are consistent between the HTML textarea and Rust, despite the different character encodings used, and avoid false negatives.

**Comment by jprochazk** [comment]
I'm not totally sure if I want to directly support this as a rule. I think in this case it might make sense because strings on the web are commonly encoded as UTF-16, but I don't want to directly add a rule for every possible use case, as each new rule means more maintenance effort.

That being said, even if the crate doesn't directly support it at the moment, Rust `str` has an [encode_utf16](https://doc.rust-lang.org/std/primitive.str.html#method.encode_utf16) method which could be used as a custom validator here:

```rust
/// Validates that when `v` is encoded as utf-16, its length in code points is `>= MIN` and `<= MAX`.
pub fn length_utf16<const MIN: usize, const MAX: usize>(v: &str, _: &()) -> garde::Result {
    let len = v.encode_utf16().count();
    if len < MIN {
        return Err(garde::Error::new(format!("length is lower than {MIN}")));
    }
    if len > MAX {
        return Err(garde::Error::new(format!("length is greater than {MAX}")));
    }
    Ok(())
}
```

Usage:
```rust
#[derive(garde::Validate)]
struct Test<'a> {
    #[garde(custom(length_utf16::<32, 65535>))]
    field: &'a str,
}
```

**Comment by LeoniePhiline** [comment]
### Side note:

The length calculations differ in more than just the UTF variant.

The length validator [counts Unicode code points](https://github.com/jprochazk/garde/blob/main/garde/src/rules/length.rs#L71-L87), while `v.encode_utf16().count()` (and the HTML form validation) [count code units](devdoc.net/web/developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/length.html#Description).

This causes vast differences in length calculations for emoji: 
🖐🏽 uses 2 Unicode code points, but 4 UTF-16 code units.
