### ISSUE TITLE
Error: compiling clean example of axum_garde.

### ISSUE THREAD

**Issue by df51d** [jprochazk/garde#45]
### Issue Description
When compiling `axum_garde` version 0.11.2, the following error occurs:
```
error[E0404]: expected trait, found derive macro `Validate`
  --> /home/p/.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum_garde-0.11.2/src/with_validation.rs:67:23
   |
67 |     Extractor::Inner: Validate<Context = Context>,
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not a trait
   |
help: consider importing this trait instead
   |
1  + use garde::validate::Validate;
   |

For more information about this error, try `rustc --explain E0404`.
error: could not compile `axum_garde` (lib) due to previous error
```
Tried to manually add this `use` but then there are further errors.
### Reproducible State
To reproduce this error, please follow these steps:
```bash
# Assuming you have Rust and Cargo installed
$ cargo new foo
$ echo 'axum = "0.6.18"
axum_garde = "0.11.2"
garde = "0.11.2"
serde = "1.0.163"
tokio = { version = "1.28.1", features = ["full"] }' >> foobar/Cargo.toml
$ cd foobar && cargo b
```
### Environment
    $ rustc --version
    rustc 1.71.0-nightly (a368898de 2023-05-02)

**Comment by jprochazk** [comment]
That seems really strange, almost like a compiler bug. I can't reproduce the error:

```
$ rustc --version
rustc 1.71.0-nightly (e77366b57 2023-05-16)

$ cargo new foo
$ echo 'axum = "0.6.18"
axum_garde = "0.11.2"
garde = "0.11.2"
serde = "1.0.163"
tokio = { version = "1.28.1", features = ["full"] }' >> foo/Cargo.toml
$ cd foo && cargo b
<snip>
    Finished dev [unoptimized + debuginfo] target(s) in 7.38s
```

A few things you could try:
1. Stable toolchain
2. Update to latest nightly
3. Fork the repo, apply the change the compiler is suggesting, and see if that fixes it

**Comment by df51d** [comment]
It seems that something somewhere went really wrong. After removal, /target, ~/.cargo/register and etc., everything works as expected.
