### ISSUE TITLE
Required rule

### ISSUE THREAD

**Issue by jprochazk** [jprochazk/garde#5]
Special case of `length(min=1)` that also works for `Option`.

```rust
#[derive(Validation)]
struct Test {
  #[garde(required)] // equivalent to `#[garde(length(min=1))]`
  items: Vec<String>,
  #[garde(required)] // checks that `Option::is_some(&value) == true`
  value: Option<String>,
}
```

The actual semantics will be based on an `IsEmpty` trait that will be implemented for various containers (`std::collections`, `Vec`, string types, `Option<T>`), and will be guaranteed `O(1)`.

**Comment by Altair-Bueno** [comment]
I don't think this is a good idea.

- `len()` on strings, vectors, etc already is O(1)
- From the docs "every [Option](https://doc.rust-lang.org/std/option/enum.Option.html) is either [Some](https://doc.rust-lang.org/std/option/enum.Option.html#variant.Some) and contains a value, or [None](https://doc.rust-lang.org/std/option/enum.Option.html#variant.None), and does no" (https://doc.rust-lang.org/std/option/index.html). By definition, the type might be empty. `required` would make things confusing

**Comment by jprochazk** [comment]
> I don't think this is a good idea.

`required` is to `Option` what `length(min=1)` is to `String`. Not to mention that `validator` already supports this, and people actually use it. :)

**Comment by Altair-Bueno** [comment]
Given that garde is a new crate that has already broken backwards compatibility, it would be wise to actually spend some time on API design and ergonomics. The original author has stated that he never actually used his own crate, and it shows on things like this.

**Comment by jprochazk** [comment]
After thinking this over a bit, I can't think of a proper use-case for this. If you want a field to be required, it should not be wrapped in `Option`, so that it fails during deserialization.

...but there were people using it ([Keats/validator#172](https://www.github.com/Keats/validator/issues/172), [Keats/validator#21](https://www.github.com/Keats/validator/issues/21), [Keats/validator#200](https://www.github.com/Keats/validator/issues/200), [Keats/validator#128](https://www.github.com/Keats/validator/issues/128)), so maybe I'm just missing something. I also can't think of any downsides to adding this, so I still plan to implement this, but only for `Option`, not for other containers.

**Comment by Altair-Bueno** [comment]
From Keats/validator#21 I can see people are using `required` for builder patterns (they don't know [derive_builder](https://docs.rs/derive_builder/latest/derive_builder/)?)

> However, one of the primary validations I would want to perform on my structs would be Option::is_some, basically to check whether a builder-style struct is in a valid state.

Also, searching for `validator(required)` yields only 77 files ([source](https://github.com/search?q=lang%3Arust+%2F%23%5C%5Bvalidate%5C%28required%5C%29%5C%5D%2F&type=code)). Some of the usages are [extremely wacky](https://github.com/RadikalSternchen/grantee/blob/55b9bf4d58d8c4a3630874a7e51b076d0828ec64/src/model.rs#L238). [Another](https://github.com/naokirin/fakey-cognito/blob/a0426f7d5e5a8e03abb6eb82e0bbb36cc37d28da/src/user_pools/admin_add_user_to_group.rs#L38)

>  I also can't think of any downsides to adding this

The main reasons why I think its a bad idea

1. More code to maintain
2. Endorsing what I would call a bad smell

**Comment by jprochazk** [comment]
I've decided to support it as of [`v0.12`](https://github.com/jprochazk/garde/releases/tag/v0.12.0). I understand that it's a code smell, but it's preventing people from migrating to `garde`. It costs me nothing to support it as well, since the rule is extremely simple and only implemented for `Option`.
