### ISSUE TITLE
Validate iterables of basic types (String, integers, …)

### ISSUE THREAD

**Issue by jirutka** [jprochazk/garde#53]
Can you please add support for validating iterables (e.g. vec) of basic types, such as String, integers, …? For example:

```rs
#[derive(Validate)]
struct User {
    #[garde(ascii, length(min=3, max=25))]
    usernames: Vec<String>,
    #[garde(pattern("^[a-f0-9]{32}$"))]
    things: Vec<String>,
}
```

**Comment by jprochazk** [comment]
This would be addressed by https://github.com/jprochazk/garde/issues/23 (`inner` modifier)

**Comment by jprochazk** [comment]
Added the `inner` modifier in [`v0.12`](https://github.com/jprochazk/garde/releases/tag/v0.12.0). For now, it's only implemented for `&[T]`, `[T; N]` and `Vec<T>`.
