### ISSUE TITLE
Why is using dive within inner not allowed?

### ISSUE THREAD

**Issue by ciresnave** [jprochazk/garde#58]
I wasn't sure where else to ask this question so I'm filing an issue.  

I have a struct with a Vec of a type that is already set up to be validated.  Here's a simpler example of what I ran into:

```
#[derive(Validate)]
struct MyInnerStruct {
    #[garde(ascii, length(min=3, max=25))]
    a_variable: String,
}

#[derive(Validate)]
struct MyOuterStruct {
    #[garde(inner(dive))]
    a_vec: Vec<MyInnerStruct>,
}
```

If I'm understanding dive correctly, it tells garde to validate the type it is applied to.  If I'm understanding inner correctly, it tells garde to run each validation passed to it as a parameter on the contained value(s).  Why, then, is it not allowed to nest dive within inner as I have above?  Shouldn't that be the correct way to tell garde to call validate on each item within the vector?

I see within the docs under the "Implementing Validate" section that I can manually implement Validate on MyOuterStruct to accomplish this...but why can't I simply use #[garde(inner(dive))]?

Thanks in advance for your answer and thank you for garde.  Even with this, I like garde.

**Comment by jprochazk** [comment]
Yes, you understand `dive` correctly, but `dive` may only be applied at the top level. That will do what you want it to do in this case, so you just have to remove the `inner`.

To clarify the difference between `inner` and `dive`:
- `dive` exists for calling `validate` on `T` where `T: Validate`. The `T` here just happens to be a `Vec`.
- `inner` exists to allow applying rules on the `String` in `Vec<String>`. (`String` may be replaced by any other type that directly implements the rules from `garde::rules`)

The job of `inner` was previously accomplished by creating a `String` newtype and putting `dive` on the `Vec<StringNewtype>`.

The exact behavior here may make more sense upon inspecting the output of the proc macro. If you remove the `inner` wrapper:

```diff
 #[derive(Validate)]
 struct MyInnerStruct {
     #[garde(ascii, length(min=3, max=25))]
     a_variable: String,
 }
 
 #[derive(Validate)]
 struct MyOuterStruct {
-    #[garde(inner(dive))]
+    #[garde(dive)]
     a_vec: Vec<MyInnerStruct>,
 }
```

The proc macro no longer emits any errors, and generates the following code:

<details><summary>Expansion</summary>

```rust
impl ::garde::Validate for MyOuterStruct {
    type Context = ();
    #[allow(clippy::needless_borrow)]
    fn validate(
        &self,
        __garde_user_ctx: &Self::Context,
    ) -> ::core::result::Result<(), ::garde::error::Errors> {
        ({
            let Self { a_vec } = self;
            ::garde::error::Errors::fields(|__garde_errors| {
                __garde_errors.insert("a_vec", {
                    let __garde_binding = &*a_vec;
                    ::garde::error::Errors::nested(
                        ::garde::error::Errors::empty(),
                        ::garde::validate::Validate::validate(&*__garde_binding, __garde_user_ctx)
                            .err()
                            .unwrap_or_else(::garde::error::Errors::empty),
                    )
                });
            })
        })
        .finish()
    }
}
```

</details>

In the wall of barely legible machine-generated code, there's a call to `Validate::validate` on the `a_vec` field (referred to as `__garde_binding` for reasons). If you then look for the implementation of `Validate` on `Vec`, you'll find it here (hidden in a macro used to implement the same behavior for many similar containers):

https://github.com/jprochazk/garde/blob/24562ec713218315ddd56939e37a955c42a78eb2/garde/src/validate.rs#L130-L136

That is to say that calling `validate` on a `Vec` will call `validate` on each item already, and collect the errors (if multiple items fail checks, _all_ of the errors will be collected). There's nothing else for the `validate` impl on `Vec` to do, after all.

To add a bit more context, you can apply `dive` on any type implementing `Validate`:

```rust
#[derive(Validate)]
struct Foo {
    #[garde(range(min=1, max=10))]
    v: i32,
}

#[derive(Validate)]
struct Bar {
    #[garde(dive)]
    foo: Foo
}
```

You can also freely combine `dive` with other top-level rules (if the type implements them):

```diff
 #[derive(Validate)]
 struct MyInnerStruct {
     #[garde(ascii, length(min=3, max=25))]
     a_variable: String,
 }
 
 #[derive(Validate)]
 struct MyOuterStruct {
-    #[garde(dive)]
+    #[garde(dive, length(min = 1))]
     a_vec: Vec<MyInnerStruct>,
 }
```

<details><summary>Expansion</summary>

```rust
impl ::garde::Validate for MyOuterStruct {
    type Context = ();
    #[allow(clippy::needless_borrow)]
    fn validate(
        &self,
        __garde_user_ctx: &Self::Context,
    ) -> ::core::result::Result<(), ::garde::error::Errors> {
        ({
            let Self { a_vec } = self;
            ::garde::error::Errors::fields(|__garde_errors| {
                __garde_errors.insert("a_vec", {
                    let __garde_binding = &*a_vec;
                    ::garde::error::Errors::nested(
                        ::garde::error::Errors::simple(|__garde_errors| {
                            if let Err(__garde_error) = (::garde::rules::length::apply)(
                                &*__garde_binding,
                                (1usize, usize::MAX),
                            ) {
                                __garde_errors.push(__garde_error)
                            }
                        }),
                        ::garde::validate::Validate::validate(&*__garde_binding, __garde_user_ctx)
                            .err()
                            .unwrap_or_else(::garde::error::Errors::empty),
                    )
                });
            })
        })
        .finish()
    }
}
```

</details>

In the above expansion, on top of the `validate` call on `a_vec`, there is now a `length::apply` call on the same `a_vec` field.

**Comment by ciresnave** [comment]
Wow!  Thank you.  The solution is both elegant and easy.  Would you consider adding that information to the Readme?  I would think a single sentence would bypass this confusion for future users.  Maybe something to the effect of, "If applied to a standard container, dive will validate each item within the container".  Today was my first day playing with garde and I have replaced my validation code in several large projects with it.  This hang up with dive already diving into contained items was the only thing that wasn't immediately obvious to me.

Thanks again for garde.
