### ISSUE TITLE
Make `NoKey` public

### ISSUE THREAD

**Issue by skreborn** [jprochazk/garde#72]
I'm trying to create a custom container type with support for `#[garde(inner)]`. Implementing `Inner` is easy enough, but since the type is an enum not unlike `Option`, it doesn't have a key for its contained value.

The workaround for now is simply to specify a bogus key as a static string, but obviously the semantically correct thing to do would be to use `NoKey` as the `Key` type within `Inner`.

I'm seeing no immediate reason `NoKey` couldn't just be public, so I'm putting in a request for it to be made so.

```rust
#[derive(Debug)]
enum Perhaps<T> {
  NoWay,
  Definitely(T),
}

impl<T> Inner<T> for Perhaps<T> {
  type Key = &'static str; // I'd like to replace this with `NoKey`

  fn validate_inner<F>(&self, mut f: F)
  where
    F: FnMut(&T, &Self::Key),
  {
    if let Self::Definitely(item) = self {
      f(item, &"value") // And use it here
    }
  }
}
```

**Comment by jprochazk** [comment]
Unless I'm missing something, it already is `pub`, and constructible via `::default()`:

```rust
#[derive(Debug)]
enum Perhaps<T> {
  NoWay,
  Definitely(T),
}

impl<T> garde::rules::inner::Inner<T> for Perhaps<T> {
  type Key = garde::error::NoKey;

  fn validate_inner<F>(&self, mut f: F)
  where
    F: FnMut(&T, &Self::Key),
  {
    if let Self::Definitely(item) = self {
      f(item, &garde::error::NoKey::default())
    }
  }
}

#[derive(garde::Validate)]
struct Test {
  #[garde(inner(range(min = 10)))]
  v: Perhaps<u32>,
}
```

**Comment by skreborn** [comment]
Yes, you're quite right, it's technically `pub`, but my tooling actively (and understandably) discourages its use because of its `#[doc(hidden)]` annotation.

**Comment by jprochazk** [comment]
Done in [v0.16.1](https://github.com/jprochazk/garde/releases/tag/v0.16.1)
