### ISSUE TITLE
Why seal PathComponentKind ?

### ISSUE THREAD

**Issue by Wicpar** [jprochazk/garde#80]
The latest version breaks my usecase where i use parsed iso lang keys: 

```rust
#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema, Validate)]
#[serde(rename_all = "snake_case")]
pub struct I18nStruct {
    #[garde(dive)]
    pub i18n: HashMap<Lang, I18nName>,
}
```

why seal it ? people may need to have custom string-representable keys.

**Comment by jprochazk** [comment]
Can't remember why I did it. Maybe I was being overly defensive or something. Seems fine to unseal it
